version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - springmysql-net
  app:
    depends_on:
      - mysql
    build: ./
    restart: on-failure
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "team-splitter.db.mysql.url"  : "jdbc:mysql://mysql:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    networks:
      - springmysql-net
    stdin_open: true
    tty: true

volumes:
  mysql:

networks:
  springmysql-net: