version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - springmysql-net
  app:
    depends_on:
      - mysql
    build: ./team-splitter-app
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "telegram.bot.token": "${TELEGRAM_BOT_TOKEN}",
        "team-splitter.db.mysql.url"  : "jdbc:mysql://mysql:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false",
         "team-splitter.db.mysql.user" : "${MYSQLDB_USER}",
         "team-splitter.db.mysql.password" : "${MYSQLDB_ROOT_PASSWORD}",
         "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect"
      }'
    volumes:
      - .m2:/root/.m2
    networks:
      - springmysql-net
    stdin_open: true
    tty: true

  backend:
    depends_on:
      - mysql
    build: ./team-splitter-server
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
         "team-splitter.db.mysql.url"  : "jdbc:mysql://mysql:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false",
          "team-splitter.db.mysql.user" : "${MYSQLDB_USER}",
          "team-splitter.db.mysql.password" : "${MYSQLDB_ROOT_PASSWORD}",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect"
       }'
    networks:
      - springmysql-net
    stdin_open: true
    ports:
      - "8080:8080"

volumes:
  mysql:

networks:
  springmysql-net: