apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
  labels:
    app: team-splitter-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-splitter-bot
  template:
    metadata:
      labels:
        app: team-splitter-bot
    spec:
      containers:
        - name: team-splitter-bot
          image: mukhanovmax/team-splitter-bot:1.20
          env:
            - name: TEAM-SPLITTER_DB_MYSQL_URL
              value: jdbc:mysql://mysql-service:3306/team-splitter?allowPublicKeyRetrieval=true&useSSL=false
            - name: TEAM-SPLITTER_DB_MYSQL_USER
              value: root
            - name: TEAM-SPLITTER_DB_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: team-splitter-secret
                  key: telegram-bot-token
            - name: GAME_SCHEDULER_ENABLED
              value: false
            - name: GAME_SCHEDULER_CHAT_ID
              value: -1001333858606
            - name: GAME_SCHEDULER_TASK_PERIODINSECONDS
              value: 300
