apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team-splitter-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: teamsplitter.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 9000